### ISSUE TITLE
Clock Freq isn't being set to max for I2C mode

### ISSUE THREAD

**Issue by JoelEB** [sparkfun/SparkFun_Micro_OLED_Arduino_Library#11]
Discovered that the I2C 400000L clock frequency is defined in the hardware.cpp file, but it is never set. Need to add this line below Wire.begin(): Wire.setClock(I2C_FREQ); Makes I2C mode noticeably faster.

**Comment by nseidle** [comment]
I2C frequency should be set by the user in main sketch because we don't know what other, possibly slower, devices may be on the bus. I'm removing define from hardware.cpp.
