### ISSUE TITLE
Inaccurate line tracing

### ISSUE THREAD

**Issue by buckle2000** [sparkfun/SparkFun_Micro_OLED_Arduino_Library#12]
https://gist.github.com/buckle2000/68dad3f24613d37625e9c2f590dd3f52

Although the two lines **should** be symmetrical...

![_20170515175419](https://cloud.githubusercontent.com/assets/10850402/26052289/8d73cf70-3997-11e7-8fdb-7583d33b509c.jpg)

But in reality, one line is **one pixel** offset, above the other.

**Comment by PaulZC** [comment]
Hi @buckle2000 ,

Thank you for raising this issue - and apologies for the very slow reply.

There was a small bug in the ```line``` function which meant that the last pixel was not being plotted. The offending line was [this one](https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library/commit/0244efeb42c3606d4da14af66fe0723b2f450752#diff-d84db23f582c7e261461fcbe7d58b3734c77872892fd2cb17e502647fd42197bR639). The equals was missing.

I've fixed this in version 1.2.10 and have added a new example (Example9) which demonstrates the correction. If you enable Serial debug messages using ```enableDebugging```, you will see the coordinates of each pixel as it gets plotted.

Thanks again for spotting this.
Very best wishes,
Paul
