### ISSUE TITLE
Example mistakenly uses `oled.getFontWidth()` instead of `getFontHeight()`

### ISSUE THREAD

**Issue by georgestephanis** [sparkfun/SparkFun_Micro_OLED_Arduino_Library#17]
https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library/blob/6ccbba3deb1936ea34ce9319320bb4e321c3da03/examples/MicroOLED_Demo/MicroOLED_Demo.ino#L322-L324

**Comment by oclyke** [comment]
Fixed with c768ea4
