### ISSUE TITLE
for I2C dcPin configured 

### ISSUE THREAD

**Issue by manitou48** [sparkfun/SparkFun_Micro_OLED_Arduino_Library#19]
For I2C mode, in begin() in  	SFE_MicroOLED.cpp, dcPin is configured though not used or set.  Default value of 0, results in pin 0 being configured with pinMode()

ref: https://forum.pjrc.com/threads/52711-Trouble-with-Serial-between-2-Teensy-s?p=181249&viewfull=1#post181249

**Comment by nseidle** [comment]
Well look at that. Good find! Thanks for the feedback.

pinMode for dcPin moved into SPI init. Should not be an issue any more. Version rolled so you should be able to pull v1.2.1 from the lib manager in a few hours. Please let me know if you find any other issues.

**Comment by manitou48** [comment]
On Sun, Jun 10, 2018 at 07:27:55AM -0700, Nathan Seidle wrote:
> Well look at that. Good find! Thanks for the feedback.
> 
> pinMode for dcPin moved into SPI init. Should not be an issue any more. Version rolled so you should be able to pull v1.2.1 from the lib manager in a few hours. Please let me know if you find any other issues.
> 
> 
> 
> -- 

I think parallelWrite also expects that dcPin mode has been set to OUPUT.

**Comment by nseidle** [comment]
Ah, thanks. Yep. Fixed.
