### ISSUE TITLE
Hide the splashcreen

### ISSUE THREAD

**Issue by DaAwesomeP** [sparkfun/SparkFun_Micro_OLED_Arduino_Library#3]
I removed the one second delay, but I still see the splashscreen briefly every time I turn it on. Is there a way to disable this without modifying too much of the library code?

**Comment by jimblom** [comment]
If you start your setup with these few lines of code:

``` c
oled.begin();
oled.clear(PAGE);
oled.display();
```

That should clear the splashscreen out of the display buffer before displaying it.

**Comment by DaAwesomeP** [comment]
That did it! Thanks.
