### ISSUE TITLE
Ignoring library with bad name

### ISSUE THREAD

**Issue by maker-git714** [sparkfun/SparkFun_Micro_OLED_Arduino_Library#31]
Arduino board: Sparkfun Red Board

Arduino IDE version (found in Arduino -> About Arduino menu): **1.8.13
**
**When launching Arduino IDE on MacOS 10.15.7, Ubuntu 20.04 LTS and Mint Linux 20.1 Ulyssa, error message encountered- see attached screenshot
**
![Screenshot from 2021-03-27 09-33-43](https://user-images.githubusercontent.com/71176174/112772383-75750300-8ffe-11eb-8028-253d02710897.jpg)

**Comment by PaulZC** [comment]
Hi @maker-git714 ,
It looks like you have installed the library twice, or have downloaded it twice and installed the second copy?
If you remove the (1) from the folder name, all should be well.
Best wishes,
Paul
