### ISSUE TITLE
Text not displayed with wemos d1mini (ESP8266)

### ISSUE THREAD

**Issue by landru29** [sparkfun/SparkFun_Micro_OLED_Arduino_Library#8]
Text is not displayed when using the wemos oled shield. here is the code I use:

```
  oled.begin();

  oled.clear(ALL);  
  oled.clear(PAGE);
  oled.display();

  oled.setCursor(0,0);
  oled.setFontType(1);
  oled.print("Hello world");
  oled.display(); 
```

I could fix it by deleting keyword PROGMEM from font files. It seams that PROGMEM makes it crash
(https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library/blob/master/src/util/7segment.h#L34 for instance)

here is my fork: https://github.com/landru29/SparkFun_Micro_OLED_Arduino_Library

**Comment by jimblom** [comment]
Should be fixed with the latest commit.
